version: "3.9"
services:
  db:
    platform: linux/x86_64
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  oxid_shop:
    image: endereco/oxid-6.4:latest
    container_name: oxid_shop
    volumes:
      - ./:/var/www/html/source/modules/endereco/endereco-oxid6-client
    ports:
      - 80:80
    depends_on:
      db:
        condition: service_healthy
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080